# Computes a build fingerprint for co-working version-gating (Collab/Session) and writes it into
# a generated header. Hashes the GML source CppGen consumes (same files CppGen itself watches for
# reconfiguring - see CPPGEN_INVENTORY_GLOBS in CMakeLists.txt) plus this project's own protocol
# code under Collab/. Two builds compiled from identical source produce an identical fingerprint;
# anything different - a different GML version, or a different Collab/ protocol revision -
# produces a different one, so Session refuses to let them join the same co-working session.
#
# Invoked via: cmake -DSOURCE_DIR=... -DOUTPUT_HEADER=... -P GenerateFingerprint.cmake

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_HEADER)
	message(FATAL_ERROR "GenerateFingerprint.cmake requires -DSOURCE_DIR=<repo root> -DOUTPUT_HEADER=<path>")
endif()

file(GLOB_RECURSE FINGERPRINT_INVENTORY LIST_DIRECTORIES FALSE
	"${SOURCE_DIR}/GmProject/*.gml"
	"${SOURCE_DIR}/GmProject/*.yy"
	"${SOURCE_DIR}/CppProject/Collab/*.hpp"
	"${SOURCE_DIR}/CppProject/Collab/*.cpp"
)
list(SORT FINGERPRINT_INVENTORY)

set(FINGERPRINT_CONCAT "")
foreach(FINGERPRINT_FILE ${FINGERPRINT_INVENTORY})
	file(SHA256 "${FINGERPRINT_FILE}" FINGERPRINT_FILE_HASH)
	string(APPEND FINGERPRINT_CONCAT "${FINGERPRINT_FILE_HASH}")
endforeach()
string(SHA256 BUILD_FINGERPRINT "${FINGERPRINT_CONCAT}")

set(HEADER_CONTENT
"#pragma once
// Auto-generated by Collab/GenerateFingerprint.cmake - do not edit, and do not commit (build artifact).
#define COLLAB_BUILD_FINGERPRINT \"${BUILD_FINGERPRINT}\"
")

# Avoid touching the file (and forcing a recompile of everything that includes it) when nothing
# actually changed.
set(EXISTING_CONTENT "")
if(EXISTS "${OUTPUT_HEADER}")
	file(READ "${OUTPUT_HEADER}" EXISTING_CONTENT)
endif()

if(NOT EXISTING_CONTENT STREQUAL HEADER_CONTENT)
	file(WRITE "${OUTPUT_HEADER}" "${HEADER_CONTENT}")
endif()
